### ISSUE TITLE
Loading model

### ISSUE THREAD

**Issue by ChristianEschen** [bonlime/keras-deeplab-v3-plus#11]
Hi

I would like to load the model after training.
I use the code:

model = load_model('deeplabmode.h5',
                   custom_objects={'BilinearUpsampling':BilinearUpsampling},)

Unfortunately I receive the following error;

  File "/XYZ/deeplab_model_2D.py", line 46, in __init__
    super(BilinearUpsampling, self).__init__(**kwargs)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 293, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'size')

I think this has to do with the definition of the BilinearUpsampling layer. Any ideas?

The full log is here:

Using TensorFlow backend.
Traceback (most recent call last):
  File "predict_full_img_deeplab.py", line 85, in <module>
    'dice_coef':dice_coef, 'tf':tf,'BilinearUpsampling':BilinearUpsampling},
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 2514, in from_config
    process_layer(layer_data)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 2514, in from_config
    process_layer(layer_data)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 146, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 1271, in from_config
    return cls(**config)
  File "XYZ/deeplab_model_2D.py", line 46, in __init__
    super(BilinearUpsampling, self).__init__(**kwargs)
  File "/home/christian/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 293, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'size')

**Comment by bonlime** [comment]
It's definitely a bug. Will fix it ASAP

**Comment by ChristianEschen** [comment]
Turns out it is possible to load the model weights and the model using the following.

model = Model(inputs=[model_input], outputs=[outputs])
model.load_weights(model_name)

However, this goes wrong then using multiple GPU's giving the following error code:

Traceback (most recent call last):
    model.load_weights(model_name)
  File "/home/s123656/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/s123656/anaconda3/envs/myjob1/lib/python3.5/site-packages/keras/engine/topology.py", line 3354, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 294 layers.
