### ISSUE TITLE
Can I convert a custom-trained original TF models to keras weights by using "extract_weights.py"?

### ISSUE THREAD

**Issue by QuantumLiu** [bonlime/keras-deeplab-v3-plus#61]
I'm training a deeplabv3 model using [originnal repo](https://github.com/tensorflow/models/tree/master/research/deeplab), backbone is mobilenet, trained on ADE20k. I want to concert it to a keras model by using your code, is that available?

**Comment by QuantumLiu** [comment]
I can't extract and load weights from this [checkpoint ](http://download.tensorflow.org/models/deeplabv3_xception_ade20k_train_2018_05_29.tar.gz)
I edited extract_weights.py as follow:
```
from __future__ import print_function

import os
import numpy as np
import tensorflow as tf
from keras.utils.data_utils import get_file


def get_xception_filename(key):
    """Rename tensor name to the corresponding Keras layer weight name.
    # Arguments
        key: tensor name in TF (determined by tf.variable_scope)
    """
    filename = str(key)
    filename = filename.replace('/', '_')
    filename = filename.replace('xception_65_', '')
    filename = filename.replace('decoder_', '', 1)
    filename = filename.replace('BatchNorm', 'BN')
    if 'Momentum' in filename:
        return None
    if 'entry_flow' in filename or 'exit_flow' in filename:
        filename = filename.replace('_unit_1_xception_module', '')
    elif 'middle_flow' in filename:
        filename = filename.replace('_block1', '')
        filename = filename.replace('_xception_module', '')

    # from TF to Keras naming
    filename = filename.replace('_weights', '_kernel')
    filename = filename.replace('_biases', '_bias')

    return filename + '.npy'


def get_mobilenetv2_filename(key):
    """Rename tensor name to the corresponding Keras layer weight name.
    # Arguments
        key: tensor name in TF (determined by tf.variable_scope)
    """
    filename = str(key)
    filename = filename.replace('/', '_')
    filename = filename.replace('MobilenetV2_', '')
    filename = filename.replace('BatchNorm', 'BN')
    if 'Momentum' in filename:
        return None

    # from TF to Keras naming
    filename = filename.replace('_weights', '_kernel')
    filename = filename.replace('_biases', '_bias')

    return filename + '.npy'


def extract_tensors_from_checkpoint_file(filename, output_folder='weights', net_name=None):
    """Extract tensors from a TF checkpoint file.
    # Arguments
        filename: TF checkpoint file
        output_folder: where to save the output numpy array files
    """
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    reader = tf.train.NewCheckpointReader(filename)

    for key in reader.get_variable_to_shape_map():
        # convert tensor name into the corresponding Keras layer weight name and save
        if net_name == 'xception':
            filename = get_xception_filename(key)
        elif net_name == 'mobilenetv2':
            filename = get_mobilenetv2_filename(key)
        if filename:
            path = os.path.join(output_folder, filename)
            arr = reader.get_tensor(key)
            np.save(path, arr)
            print("tensor_name: ", key)

CKPT_URL = 'http://download.tensorflow.org/models/deeplabv3_xception_ade20k_train_2018_05_29.tar.gz'
MODEL_DIR = 'models'
MODEL_SUBDIR = 'deeplabv3_ade_trainval'

if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR)

checkpoint_tar = get_file(
    'deeplabv3_xception_ade20k_train_2018_05_29.tar.gz',
    CKPT_URL,
    extract=True,
    cache_subdir='',
    cache_dir=MODEL_DIR)


checkpoint_file = os.path.join(MODEL_DIR, MODEL_SUBDIR, 'model.ckpt')
extract_tensors_from_checkpoint_file(
    checkpoint_file, net_name='xception', output_folder='weights/xception_ade')

```
Got error logs:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "extract_weights_ade.py", line 93, in <module>
    checkpoint_file, net_name='xception', output_folder='weights/xception_ade')
  File "extract_weights_ade.py", line 62, in extract_tensors_from_checkpoint_file
    reader = tf.train.NewCheckpointReader(filename)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 287, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on models\deeplabv3_ade_trainval\model.ckpt: Not found: FindFirstFile failed for: models/deeplabv3_ade_trainval : \u03f5\u0373\udcd5\u04b2\udcbb\udcb5\udcbd\u05b8\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process
```

**Comment by Tez01** [comment]
Thanks for the repo. Its very helpful.

Is the name of model's layers currently up to date with the tensorflow nomenclature?

**Comment by bonlime** [comment]
@Tez01 I don't know. I've been busy with other tasks and haven't used this repo for a long time now. It should be, but if it's not, you could open a pull request and I would merge it.
